AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: An example of deploying custom runtime written in Go

Resources:
  Hello:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: provided.al2
      Handler: bootstrap
      Timeout: 10
    Metadata:
      BuildMethod: makefile
